language: php

env:
  global:
    - secure: Yk7231s0euUDsS4An/05ImAFdUrFw8PVjCLB1CBpa9Gzq15j2T2A7npJxYyoy1QBmltffd7sxFqH98w/x4ooyz6AUyyG+l3XreN+/V1OqxUqmeHpHGhXoxxTF1WXo/NTHUBH9sLZtBMd6CCOUOlTZ+5mTV6Y4Grd9GNCAtfOj85uu5/Co01O3xAygBFTuO3bF/SuVopuWehXrtMPTY1DN9Rfz6uQ7Mw240RW7BLHQcm0VVVauVmzoiKAIXNKbfViyIeRtZixGHcAg4LO9UWQed7YCcBO9gbT9gPJvhGctoG/5lYiS10peqQfueif83YaNNsJBNZ8RVqAhFq/iXzDZQ==
    - GCR_BASE="eu.gcr.io/$MY_ORG"
    - IMAGE_TAG="${BRANCH}.${BUILD_NUMBER}"
    - NGINX_IMAGE_NAME="nginx-test"
    - PHP_IMAGE_NAME="php-test"
    - NGINX_IMAGE="${GCR_BASE}/${NGINX_IMAGE_NAME}:${IMAGE_TAG}"
    - PHP_IMAGE="${GCR_BASE}/${PHP_IMAGE_NAME}:${IMAGE_TAG}"

build:
  ci:
    - cp nginx-Dockerfile Dockerfile 
    - docker build -t "$NGINX_IMAGE" . 
    - cp php-Dockerfile Dockerfile
    - docker build -t "$PHP_IMAGE" .
  post_ci:
    - docker push "$NGINX_IMAGE"
    - docker push "$PHP_IMAGE"
integrations:
  hub:
    - integrationName: gcloud-integration    #replace with your subscription integration name
      type: gcloudKey

resources:
  - name: deploy-kubernetes-multi-container-nginx-image
    type: image
    integration: gcloud-integration    #replace with your Docker Hub integration name
    pointer:
      sourceName: "${GCR_BASE}/${NGINX_IMAGE_NAME}"  #replace with your image name on Docker Hub
    seed:
      versionName: "${IMAGE_TAG}"  #replace with your image tag on Docker Hub
    flags:
      - deploy-kubernetes-multi-container

  - name: deploy-kubernetes-multi-container-php-image
    type: image
    integration: gcloud-integration
    pointer:
      sourceName: "${GCR_BASE}/${PHP_IMAGE_NAME}"
    seed:
      versionName: "${IMAGE_TAG}"
    flags:
      - deploy-kubernetes-multi-container

#kubernetes cluster
  - name: mc-kube-cluster
    type: cluster
    integration: gcloud-integration    #replace with your Kubernetes integration name
    pointer:
      sourceName: "$GKE_CLUSTER_NAME"
      region: "$GKE_REGION"
      namespace: "test"
    flags:
     - deploy-kubernetes-multi-container

jobs:
  - name: php-kube-test_runCI
    type: runCI
    flags:
      - deploy-kubernetes-multi-container
    steps:
      - OUT: deploy-kubernetes-multi-container-nginx-image
      - OUT: deploy-kubernetes-multi-container-php-image

  - name: deploy-kubernetes-multi-container-manifest-1
    type: manifest
    flags:
      - deploy-kubernetes-multi-container
    steps:
     - IN: deploy-kubernetes-multi-container-php-image
     - IN: deploy-kubernetes-multi-container-nginx-image

  - name: dkmc-deploy-1
    type: deploy
    flags:
      - deploy-kubernetes-multi-container
    steps:
      - IN: deploy-kubernetes-multi-container-manifest-1
      - IN: mc-kube-cluster
